#!/usr/bin/env python
import numpy
import random

import math
import rospy
import tf
from threading import Event
import actionlib

from geometry_msgs.msg import PoseStamped, Point
from std_msgs.msg import String
from visualization_msgs.msg import MarkerArray, Marker
import freeplay_sandbox_msgs.msg

MAP_HEIGHT=0.335

REFERENCE_FRAME="/sandtray"


class Player(object):
    def __init__(self):
        self._tl = tf.TransformListener()
        rospy.sleep(0.5) # sleep a bit to make sure the TF cache is filled

        self._action_sub = rospy.Subscriber("sparc/selected_action", freeplay_sandbox_msgs.msg.ContinuousAction, self.on_action_received)
        self._event_sub = rospy.Subscriber("sandtray/interaction_events", String, self.on_event)
        self._nao_event_sub = rospy.Subscriber("nao/events", String, self.on_nao_event)

        self._motion = actionlib.SimpleActionClient('move_sandbox_items', freeplay_sandbox_msgs.msg.PlaygroundNavigationAction)
        self._speech_pub = rospy.Publisher("speech", String, queue_size = 5)
        self._blocking_speech_pub = rospy.Publisher("nao/blocking_speech", String, queue_size = 5)
        self._poses_pub = rospy.Publisher("poses", PoseStamped, queue_size = 5)
        self._event_pub = rospy.Publisher("nao/events", String, queue_size = 5)
        self._motion.wait_for_server()

        rospy.loginfo("Ready to play!")
        self.event_release = Event()
        self._moving_item = None
        self._waiting_speech = None
        self._waiting_pointing = None

    def run(self):
        rospy.spin()

    def on_action_received(self,action):
        if action.type == "move":
            item = action.header.frame_id

            if self._moving_item is not None:
                self.event_release.clear()
                self._motion.cancel_goal()
                if self._moving_item != item:
                    self.event_release.wait()

            pose = self.get_pose(item)
            if pose is None: # frame not published yet!
                return
            pose = pose[0], pose[1]

            pose = self._tl.transformPose("sandtray", action)
            pose =  pose.pose.position
            self._moving_item = item
            print "sending " + item + " to " + str(pose.x) + " " + str(pose.y)
            goal = freeplay_sandbox_msgs.msg.PlaygroundNavigationGoal(item=action.header.frame_id,goal=pose)
            self._motion.send_goal(goal)

        if action.type == "att":
            item = action.header.frame_id
            self._speech_pub.publish(String("Look at the "+item.split("-")[0]))
            message = PoseStamped()
            message.header.frame_id = item
            message.header.stamp = rospy.Time.now()
            self._poses_pub.publish(message)
            self._waiting_pointing=action.type

        if action.type == "fel":
            self.say_blocked("Well done", action.type)

        if action.type == "enc":
            self.say_blocked("Keep going, you can do it", action.type)

        if action.type == "rul":
            self.say_blocked("Remember, you have to feed the animals to keep them alive", action.type)

    def say_blocked(self, msg, action):
        self._blocking_speech_pub.publish(String(msg))
        self._waiting_speech = action

    def on_event(self,msg):
        if msg.data.startswith("robotrelease_"):
            self._moving_item = None
            self.event_release.set()

    def on_nao_event(self, msg):
        if msg.data == "blocking_speech_finished" and self._waiting_speech:
            self._event_pub.publish(String(self._waiting_speech + "_finished"))
            self._waiting_speech = None
        if msg.data == "pointing_finished" and self._waiting_pointing:
            self._event_pub.publish(String(self._waiting_pointing + "_finished"))
            self._waiting_pointing = None

    def get_pose(self,item, reference=REFERENCE_FRAME):
        if item not in self._tl.getFrameStrings():
            rospy.logwarn_throttle(20,"%s is not yet published." % item)
            return None

        if self._tl.canTransform(reference, item, rospy.Time(0)):
            (trans,rot) = self._tl.lookupTransform(reference, item, rospy.Time(0))
        else:
            return None
        return trans

if __name__ == "__main__":

    rospy.init_node('woz_play')

    rospy.loginfo("Initializing TF...")
    player = Player()
    player.run()
